---
http_interactions:
- request:
    method: get
    uri: http://192.168.50.2:4440/api/12/project/anvils
    body:
      encoding: US-ASCII
      string: ''
    headers:
      X-Rundeck-Auth-Token:
      - vDCT9dP6evCJYHtWoivruQtymkLTGJXq
      Accept:
      - application/xml
  response:
    status:
      code: 200
      message: OK
    headers:
      Set-Cookie:
      - JSESSIONID=1jy3ft091jv3sli5b0lh1sphz;Path=/
      Expires:
      - Thu, 01 Jan 1970 00:00:00 GMT
      X-Rundeck-Api-Xml-Response-Wrapper:
      - 'false'
      Content-Type:
      - application/xml;charset=UTF-8
      X-Rundeck-Api-Version:
      - '12'
      Transfer-Encoding:
      - chunked
      Server:
      - Jetty(7.6.0.v20120127)
    body:
      encoding: UTF-8
      string: |-
        <project url='http://192.168.50.2:4440/api/12/project/anvils'>
          <name>anvils</name>
          <description></description>
          <config>
            <property key='project.name' value='anvils' />
            <property key='project.ssh-authentication' value='privateKey' />
            <property key='service.NodeExecutor.default.provider' value='jsch-ssh' />
            <property key='resources.source.1.config.includeServerNode' value='true' />
            <property key='resources.source.1.config.generateFileAutomatically' value='true' />
            <property key='resources.source.1.config.file' value='/var/rundeck/projects/anvils/etc/resources.xml' />
            <property key='project.ssh-keypath' value='/var/lib/rundeck/.ssh/id_rsa' />
            <property key='service.FileCopier.default.provider' value='jsch-scp' />
            <property key='resources.source.1.type' value='file' />
          </config>
        </project>
    http_version: 
  recorded_at: Sat, 17 Jan 2015 20:55:45 GMT
recorded_with: VCR 2.9.3
